-- MySQL Script generated by MySQL Workbench
-- 05/12/14 15:39:58
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Movies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `duration` FLOAT NOT NULL,
  `copies` INT NULL DEFAULT 0,
  `dailyCharge` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category_has_Movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Category_has_Movies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Category_has_Movies` (
  `Category_id` INT NOT NULL,
  `Movies_id` INT NOT NULL,
  PRIMARY KEY (`Category_id`, `Movies_id`),
  INDEX `fk_Category_has_Movies_Movies1_idx` (`Movies_id` ASC),
  INDEX `fk_Category_has_Movies_Category1_idx` (`Category_id` ASC),
  CONSTRAINT `fk_Category_has_Movies_Category1`
    FOREIGN KEY (`Category_id`)
    REFERENCES `mydb`.`Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Category_has_Movies_Movies1`
    FOREIGN KEY (`Movies_id`)
    REFERENCES `mydb`.`Movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reciept`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reciept` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reciept` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `leaseDate` DATETIME NOT NULL,
  `Customer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Reciept_Customer1_idx` (`Customer_id` ASC),
  CONSTRAINT `fk_Reciept_Customer1`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `mydb`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reciept_has_Movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reciept_has_Movies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reciept_has_Movies` (
  `Reciept_id` INT NOT NULL,
  `Movies_id` INT NOT NULL,
  PRIMARY KEY (`Reciept_id`, `Movies_id`),
  INDEX `fk_Reciept_has_Movies_Movies1_idx` (`Movies_id` ASC),
  INDEX `fk_Reciept_has_Movies_Reciept1_idx` (`Reciept_id` ASC),
  CONSTRAINT `fk_Reciept_has_Movies_Reciept1`
    FOREIGN KEY (`Reciept_id`)
    REFERENCES `mydb`.`Reciept` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reciept_has_Movies_Movies1`
    FOREIGN KEY (`Movies_id`)
    REFERENCES `mydb`.`Movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Department` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codDepartment` INT NOT NULL,
  `departmentName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `birthDate` DATE NOT NULL,
  `employeeMark` VARCHAR(45) NOT NULL,
  `salary` FLOAT NOT NULL,
  `Department_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Employee_Department1_idx` (`Department_id` ASC),
  CONSTRAINT `fk_Employee_Department1`
    FOREIGN KEY (`Department_id`)
    REFERENCES `mydb`.`Department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
